### ISSUE TITLE
Latest version (0.2.5) - Undefined method PhpCsFixer\Config::create()

### ISSUE THREAD

**Issue by Jannick94** [junstyle/vscode-php-cs-fixer#151]
In the latest version (0.2.5) the extension stopped working for me. The following console error is logged to the vscode developer tools console.

```sh
PHP Fatal error:  Uncaught Error: Call to undefined method PhpCsFixer\Config::create() in /home/jannick/Workspace/verloning/.php-cs-fixer.php:139
Stack trace:
#0 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/ConfigurationResolver.php(836): include()
#1 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/ConfigurationResolver.php(229): PhpCsFixer\Console\ConfigurationResolver::separatedContextLessInclude()
#2 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/ConfigurationResolver.php(561): PhpCsFixer\Console\ConfigurationResolver->getConfig()
#3 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/ConfigurationResolver.php(406): PhpCsFixer\Console\ConfigurationResolver->getFormat()
#4 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/Command/FixCommand.php(258): PhpCsFixer\Console\ConfigurationResolver->getReporter()
#5 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/vendor/symfony/console/Command/Command.php(255): PhpCsFixer\Console\Command\FixCommand->execute()
#6 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/src/Console/Application.php(97): Symfony\Component\Console\Application->doRun()
#9 phar:///home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar/vendor/symfony/console/Application.php(149): PhpCsFixer\Console\Application->doRun()
#10 /home/jannick/.vscode/extensions/junstyle.php-cs-fixer-0.2.5/php-cs-fixer.phar(113): Symfony\Component\Console\Application->run()
#11 {main}
  thrown in /home/jannick/Workspace/verloning/.php-cs-fixer.php on line 139
```

When I downgrade to 0.2.2 the extension works as normal again.

**Comment by junstyle** [comment]
.php-cs-fixer.php  this file is config file, please go to [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and see how to config it correctly

.php-cs-fixer.php is config file of v3

PhpCsFixer\Config::create() not exists in v3,
new PhpCsFixer\Config() instead

https://github.com/FriendsOfPHP/PHP-CS-Fixer see detail
