### ISSUE TITLE
Extension crashes on undefined functions

### ISSUE THREAD

**Issue by Zankaria** [junstyle/vscode-php-cs-fixer#210]
If the extension finds an undefined function anywhere in the code, it crashes.
A formatting extension should still be able to format the callsite without crashing.

```
[
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=/home/zankaria/Projects/vichan/.php-cs-fixer.php",
  "--path-mode=override",
  "/tmp/pcf-tmp0.9215133895888903/.php-cs-fixer.php"
]
PHP Fatal error:  Uncaught Error: Call to undefined function _() in /home/zankaria/Projects/vichan/inc/config.php:565
Stack trace:
#0 /home/zankaria/Projects/vichan/inc/functions.php(145): require()
#1 /home/zankaria/Projects/vichan/inc/functions.php(20): loadConfig()
#2 /home/zankaria/Projects/vichan/vendor/composer/autoload_real.php(41): require('...')
#3 /home/zankaria/Projects/vichan/vendor/composer/autoload_real.php(45): {closure}()
#4 /home/zankaria/Projects/vichan/vendor/autoload.php(25): ComposerAutoloaderInit9ab809f218224ff51233bb0f471eb557::getLoader()
#5 /home/zankaria/Projects/vichan/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(89): require_once('...')
#6 /home/zankaria/Projects/vichan/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(91): {closure}()
#7 {main}
  thrown in /home/zankaria/Projects/vichan/inc/config.php on line 565
```

**Comment by junstyle** [comment]
how to reproduce this issue?
