### ISSUE TITLE
Set "@PER" does not exist.

### ISSUE THREAD

**Issue by jimmy-jose** [junstyle/vscode-php-cs-fixer#211]
VS code extension is giving the following error
<img width="555" alt="Screenshot 2024-02-21 at 9 57 41 PM" src="https://github.com/junstyle/vscode-php-cs-fixer/assets/20584190/7b6fd1d9-841c-4fff-83c6-9461ca927443">
General Error (or PHP minimal requirement not matched
`Set "@PER" does not exist.`

Here is the full error message: 
```
[
  "fix",
  "--using-cache=no",
  "--format=json",
  "--rules=@PER",
  "--path-mode=override",
  "/var/folders/wt/6fqt_lqn0jn7srxb10b98g2h0000gn/T/pcf-tmp0.36985781350124003/AbcHelper.php"
]
Loaded config default.

In RuleSets.php line 65:
                              
  Set "@PER" does not exist.  
                              

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
```
Version
PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.15

Its works fine when I try to fix a file by using
`./php-cs-fixer fix ../../../../app/Http/Helpers/AbcHelper.php`

Here is the config file:

```
<?php

$config = new PhpCsFixer\Config();
return $config
    ->setRules([
        '@PSR12' => true, // This is the default rule
        // This is where new rules can go
        'no_unused_imports' => true,
        'ordered_imports' => [
            'imports_order' => ['class', 'function', 'const'],
            'sort_algorithm' => 'alpha',
        ],
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
            ->exclude('Google')
            ->exclude('GPBMetadata')
            ->exclude('Grpc')
            ->exclude('Pb')
            ->exclude('app/funds/Pb')
            ->exclude('app/funds/Services/VendorLedger/Pb')
            ->exclude('app/funds/Services/Transaction/Pb')
    );
```

This is how settings.json is configured
```
 "php-cs-fixer.config": "${workspaceRoot}/project/tools/.php-cs-fixer.php",
  "php-cs-fixer.executablePath": "${workspaceRoot}/project/tools/php-cs-fixer/vendor/bin/php-cs-fixer",
  "php-cs-fixer.onsave": true,
```

I can also see this in the dev console:

```
[Extension Host]% (6) ['fix', '--using-cache=no', '--format=json', '--rules=@PER', '--path-mode=override', '/var/folders/wt/6fqt_lqn0jn7srxb10b98g2h0000gn/T/pcf-tmp0.32906320184447746/SubscriptionHelper.php']0: "fix"1: "--using-cache=no"2: "--format=json"3: "--rules=@PER"4: "--path-mode=override"5: "/var/folders/wt/6fqt_lqn0jn7srxb10b98g2h0000gn/T/pcf-tmp0.32906320184447746/SubscriptionHelper.php"length: 6[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
workbench.desktop.main.js:sourcemap:149 [Extension Host] Error: Command failed, exited with code #1
    at hE (/Users/Jimmy/.vscode/extensions/junstyle.php-cs-fixer-0.3.11/index.js:76:35364)
    at ChildProcess.y (/Users/Jimmy/.vscode/extensions/junstyle.php-cs-fixer-0.3.11/index.js:76:35194)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.onexit (node:internal/child_process:302:5)
```

<img width="968" alt="Screenshot 2024-02-21 at 10 08 44 PM" src="https://github.com/junstyle/vscode-php-cs-fixer/assets/20584190/5e3efdb1-ee1a-455f-8bdd-2bd97845c277">

**Comment by junstyle** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc%2FruleSets%2FPER.rst

read this doc about @per

**Comment by jimmy-jose** [comment]
@junstyle
From the document i can see that @PER is deprecated.
I can see in my tools/.php-cs-fixer.php 

```
<?php

$config = new PhpCsFixer\Config();
return $config
    ->setRules([
        '@PSR12' => true, // This is the default rule
        // This is where new rules can go
        'no_unused_imports' => true,
        'ordered_imports' => [
            'imports_order' => ['class', 'function', 'const'],
            'sort_algorithm' => 'alpha',
        ],
    ])
```

Not sure why @PER is being used instead of @PSR12??🤔

**Comment by junstyle** [comment]
"--rules=@PER",


you settings.json has a setting like this
```
"php-cs-fixer.rules": "@PER"
```

remove this setting.

**Comment by jimmy-jose** [comment]
My 
.vscode/settings.json

```
"php-cs-fixer.config": "${workspaceRoot}/monolith/tools/.php-cs-fixer.php",
  "php-cs-fixer.executablePath": "${workspaceRoot}/monolith/tools/php-cs-fixer/vendor/bin/php-cs-fixer",
  "php-cs-fixer.onsave": true,
```
only has these 3 lines. It does not have `php-cs-fixer.rules`

I have another `settings.json` file inside ~Users/.../Application Support/Code/User/settings.json
`"php-cs-fixer.rules": "@PER-CS2.0"`
I tried removing this line. But I am still getting the same error. @junstyle

**Comment by junstyle** [comment]
search your settings files for `@PER`

and remove this setting

**Comment by junstyle** [comment]
I got the issue. I will publish a new version

**Comment by jimmy-jose** [comment]
@junstyle 

I added this to my `.vscode/settings.json`

`"php-cs-fixer.rules": "@PSR12"`,

And it started working. Thanks you🙏🏻

**Comment by junstyle** [comment]
that's because the default rules is @PER. but      it's deprecated. now I uptate to @PER-CS. u can update to the latest version

**Comment by jimmy-jose** [comment]
@junstyle when i tried with
`"php-cs-fixer.rules": "@PER-CS" `
I was getting an error:
```
In RuleSets.php line 65:
                                 
  Set "@PER-CS" does not exist.  
```
But @PSR12 is working 🤔

**Comment by junstyle** [comment]
😅. ok set to @PSR12

**Comment by jimmy-jose** [comment]
@junstyle Wait 😅 what is happening now? Are you releasing updates as we speak?? How do I check?? Can I just remove the line(`"php-cs-fixer.rules": "@PSR12"`) from `.vscode/settings.json` and check right now if default value is working??

**Comment by junstyle** [comment]
nothing need to do if working

**Comment by junstyle** [comment]
nothing need to do if working

**Comment by jimmy-jose** [comment]
@junstyle Yeah. Looks like it only updated to `@PER-CS` now when i remove the my change in settings.json file
```
In RuleSets.php line 65:
                                 
  Set "@PER-CS" does not exist.  
```
