### ISSUE TITLE
Error on Save

### ISSUE THREAD

**Issue by aditya43** [junstyle/vscode-php-cs-fixer#22]
I'm using latest version on VS Code and I have set format on save option to true. 
However, I get following errors when I save : 

```
[Atishay-Jain.All-Autocomplete] Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
	at Function.replace (C:\Users\Aditya\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:112:25)
	at e.contentChanges.forEach (C:\Users\Aditya\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:139:41)
	at Array.forEach (native)
	at Function.handleContextChange (C:\Users\Aditya\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:138:26)
	at context.subscriptions.push.vscode_1.workspace.onDidChangeTextDocument (C:\Users\Aditya\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:224:30)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427937)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
```

**Comment by junstyle** [comment]
your error logs generated by Atishay-Jain.All-Autocomplete, not vscode-php-cs-fixer.
you can disable "Atishay-Jain.All-Autocomplete" and test again!
