### ISSUE TITLE
Cant get it work again :( 

### ISSUE THREAD

**Issue by parkour21** [junstyle/vscode-php-cs-fixer#28]
Hi , 
I tried everything but i can't get it work again. When i first installed it and set it, it worked like a charm and i was really happy. Now i'm getting this error over and over again :
 
ERR Bad argument: TypeError: Bad argument
	at ChildProcess.spawn (internal/child_process.js:294:26)
	at Object.exports.spawn (child_process.js:390:9)
	at PHPCSFixer.format (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:94:23)
	at exports.activate.context.subscriptions.push.languages.registerDocumentFormattingEditProvider.provideDocumentFormattingEdits.Promise (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:340:25)
	at Promise (<anonymous>)
	at Object.provideDocumentFormattingEdits (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:334:24)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:443:456
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:1004
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:234)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:967)

I have .php_cs file in my project and i got this in my settings 
    "php-cs-fixer.executablePath": "d://php-cs-fixer.phar"

I really need help over here because i need this took working back again cause it's awesome !

**Comment by junstyle** [comment]
can you show me full logs in dev tools?

**Comment by parkour21** [comment]
Yea , sure. Here it is. 

[Extension Host]% (5) ["d://php-cs-fixer.phar", "fix", "--using-cache=no", "C:\Users\random\AppData\Local\Temp/temp-gpeourk.php", "--config=d:\Projects\random/.php_cs"]
log.ts:165   ERR Bad argument: TypeError: Bad argument
	at ChildProcess.spawn (internal/child_process.js:294:26)
	at Object.exports.spawn (child_process.js:390:9)
	at PHPCSFixer.format (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:94:23)
	at exports.activate.context.subscriptions.push.languages.registerDocumentFormattingEditProvider.provideDocumentFormattingEdits.Promise (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:340:25)
	at Promise (<anonymous>)
	at Object.provideDocumentFormattingEdits (C:\Users\random\.vscode\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:334:24)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:443:456
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:1004
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:234)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:967)

**Comment by junstyle** [comment]
which version of you php-cs-fixer.phar?
maybe your php-cs-fixer.phar is not latest version. you can try download latest version.

**Comment by parkour21** [comment]
Just tried .. without success :(  Same error. 

"php-cs-fixer is already up to date."

**Comment by junstyle** [comment]
"php.validate.executablePath" default value is null in vsc, cause this issue.
I fixed it, you can update now.

**Comment by parkour21** [comment]
Loooolll back in a game again !!! Thanks a lot man. 
Just to mention. After updating, i error in console log that is really readable, so i managed to fix it !-> 

  [concat_space] Invalid configuration: The option "spacing" with value "variable" is invalid. Accepted values are: "  
  one", "none".       

Thank you so much!
